spring.application.name=fastservice

server.port=${PORT:8080}

spring.mongodb.uri=${MONGODB_URI}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.disable-swagger-default-url=true
