spring.application.name=fastservice

spring.mongodb.uri=mongodb+srv://nathanrodrigues07:mJHWZIu1NLWDgQOC@cluster0.fyxicjt.mongodb.net/FastService?retryWrites=true&w=majority&appName=Cluster0

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.disable-swagger-default-url=true
